### ISSUE TITLE
Insights are never rerendered

### ISSUE THREAD

**Issue by Narinderg** [gooddata/gooddata-ui-sdk#2072]
There is one issue we are facing with InsightView.
There is one react component where we are showing InsightViews. In case that component is rerendered, Insightviews are never displayed again.
It seems issue somewhere around contentRect used in HighChartRenderer. In case of rerendering, height inside contentRect is always showing as 0.

**Comment by no23reason** [comment]
Hi @Narinderg please make sure the container of the `InsightView` has some height specified. Please see the [examples](https://gdui-examples.herokuapp.com/insightView/insightView-by-identifier) and [documentation](https://sdk.gooddata.com/gooddata-ui/docs/visualization_component.html) for more details. You can also use `min-height` instead of `height`. That will make sure the content of the `InsightView` is always visible.

**Comment by Narinderg** [comment]
> Hi @Narinderg please make sure the container of the `InsightView` has some height specified. Please see the [examples](https://gdui-examples.herokuapp.com/insightView/insightView-by-identifier) and [documentation](https://sdk.gooddata.com/gooddata-ui/docs/visualization_component.html) for more details. You can also use `min-height` instead of `height`. That will make sure the content of the `InsightView` is always visible.

Giving min-height doesnt actually give a permanent solution. Setting min-height, still some of the insights doesn't get rendered and some of the insights gets extra width.

**Comment by no23reason** [comment]
Can you please share some code sample so that we can investigate what might be going wrong?

**Comment by kandl** [comment]
Closing the issue due to long inactivity.
